Models/client_files.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_files
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string content_type { get; set; }
        public byte[] data { get; set; }
        public int user_id { get; set; }
        public bool checked_file { get; set; }
    
        public virtual client_data client_data { get; set; }
    }
}

Controllers/client_filesController.cs
namespace demo.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;

    using demo.Models;

    using Microsoft.AspNet.Identity;

    [Authorize]
    public class client_filesController : Controller
    {
        private readonly demoEntities db = new demoEntities();

        // GET: client_files/Create
        public ActionResult Create()
        {
            return this.View();
        }

        // POST: client_files/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase[] postedFile)
        {
            var users = this.db.client_data.ToList();
            var userid = users.Find(x => x.AspNetUser.Id == this.User.Identity.GetUserId());
            if (userid != null)
            {
                foreach (var postedFileBase in postedFile)
                {
                    var postedFileExtension = Path.GetExtension(postedFileBase.FileName);
                if (string.Equals(postedFileExtension, ".jpg", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(postedFileExtension, ".png", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(postedFileExtension, ".gif", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(postedFileExtension, ".jpeg", StringComparison.OrdinalIgnoreCase) 
                    || string.Equals(postedFileExtension,".pdf",StringComparison.OrdinalIgnoreCase))
                {
                    byte[] bytes;
                    using (var br = new BinaryReader(postedFileBase.InputStream))
                    {
                        bytes = br.ReadBytes(postedFileBase.ContentLength);
                    }

                    this.db.client_files.Add(
                        new client_files
                            {
                                name = Path.GetFileName(postedFileBase.FileName),
                                content_type = postedFileBase.ContentType,
                                data = bytes,
                                user_id = userid.Id,
                                checked_file = false
                            });
                }

                this.db.SaveChanges();
                }
                
                return this.RedirectToAction("Index");
            }

            return this.View(postedFile);
        }

        // GET: client_files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var client_files = this.db.client_files.Find(id);
            if (client_files == null) return this.HttpNotFound();
            return this.View(client_files);
        }

        // POST: client_files/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var client_files = this.db.client_files.Find(id);
            this.db.client_files.Remove(client_files);
            this.db.SaveChanges();
            return this.RedirectToAction("Index");
        }

        // GET: client_files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var client_files = this.db.client_files.Find(id);
            if (client_files == null) return this.HttpNotFound();
            return this.View(client_files);
        }

        // GET: client_files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var client_files = this.db.client_files.Find(id);
            if (client_files == null) return this.HttpNotFound();
            this.ViewBag.user_id = new SelectList(this.db.client_data, "Id", "first_name", client_files.user_id);
            return this.View(client_files);
        }

        // POST: client_files/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "Id,name,content_type,data,user_id,checked_file")]
            client_files client_files)
        {
            if (this.ModelState.IsValid)
            {
                this.db.Entry(client_files).State = EntityState.Modified;
                this.db.SaveChanges();
                return this.RedirectToAction("Index");
            }

            this.ViewBag.user_id = new SelectList(this.db.client_data, "Id", "first_name", client_files.user_id);
            return this.View(client_files);
        }

        // GET: client_files
        public ActionResult Index()
        {
            var users = this.db.client_data.ToList();
            var userid = users.Find(x => x.AspNetUser.Id == this.User.Identity.GetUserId());
            var client_files = new List<client_files>();
            var client_files1 = new List<client_files>();
            var client_files2 = new List<client_files>();
            if (userid != null)
            {
                 if (User.IsInRole("client"))
                 {
                     client_files = this.db.client_files.Include(c => c.client_data).ToList();
                     client_files1 = client_files.FindAll(x => x.user_id == userid.Id);
                     var i = 0;
                     foreach (var q2 in client_files1)
                     {
                        q2.Id = ++i;
                        client_files2.Add(q2);
                     }
                     return this.View(client_files2);
                 }
                 if (User.IsInRole("Admin") || User.IsInRole("delivery"))
                 {
                     client_files = this.db.client_files.Include(c => c.client_data).ToList();
                     var i = 0;
                     foreach (var q1 in client_files)
                     {
                         q1.Id = ++i;
                        client_files2.Add(q1);
                     }
                     return this.View(client_files2);
                 }
            }
            return this.View(client_files);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) this.db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/client_files/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<style>
    .custom-file-input::-webkit-file-upload-button {
        visibility: hidden;
    }
    .custom-file-input::before {
        content: 'Select some files';
        display: inline-block;
        background: linear-gradient(top, #f9f9f9, #e3e3e3);
        border: 1px solid #999;
        border-radius: 3px;
        padding: 5px 8px;
        outline: none;
        white-space: nowrap;
        -webkit-user-select: none;
        cursor: pointer;
        text-shadow: 1px 1px #fff;
        font-weight: 700;
        font-size: 10pt;
    }
    .custom-file-input:hover::before {
        border-color: black;
    }
    .custom-file-input:active::before {
        background: -webkit-linear-gradient(top, #e3e3e3, #f9f9f9);
    }
</style>
@using (Html.BeginForm("Create", "client_files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-5">
            Old Passport
        </div>
        <div class="col-md-5">
            <input type="file" name="postedFile" class="custom-file-input" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-5">
            visa copy
        </div>
        <div class="col-md-5">
            <input type="file" name="postedFile" class="custom-file-input" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-5">
            certificate(if any)
        </div>
        <div class="col-md-5">
            <input type="file" name="postedFile" class="custom-file-input" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-5">
            Personal photo(with white background)
        </div>
        <div class="col-md-5">
            <input type="file" name="postedFile" class="custom-file-input" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-5">
            <input type="submit" id="btnUpload" value="Upload" class="btn btn-default"/>
        </div>
    </div>


}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/client_files/Delete.cshtml
@model demo.Models.client_files

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>client_files</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.content_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checked_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checked_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.client_data.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client_data.first_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/client_files/Details.cshtml
@model demo.Models.client_files

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>client_files</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.content_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.content_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.checked_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checked_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.client_data.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client_data.first_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/client_files/Edit.cshtml
@model demo.Models.client_files

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>client_files</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.content_type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.content_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.checked_file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.checked_file)
                    @Html.ValidationMessageFor(model => model.checked_file, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/client_files/Index.cshtml
@model IEnumerable<demo.Models.client_files>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var webGrid = new WebGrid(source: Model);
}

<h2>uploaded files</h2>
<meta name="viewport" content="width=device-width"/>
<title>Index</title>
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .Grid {
        border: 1px solid #ccc;
        border-collapse: collapse;
    }

    .Grid th {
        background-color: #F7F7F7;
        font-weight: bold;
    }

    .Grid th, .Grid td {
        border: 1px solid #ccc;
        padding: 5px;
    }

    .Grid, .Grid table td { border: 0px solid #ccc; }

    .Grid object {
        cursor: pointer;
        height: 100px;
        width: 100px;
    }

    #dialog object {
        cursor: pointer;
        height: 550px;
        width: 575px;
    }
</style>
@{
    var i = 0;
}
@webGrid.GetHtml(htmlAttributes: new { id = "WebGrid", @class = "Grid" }, columns: webGrid.Columns(webGrid.Column("id", "Image Id"),webGrid.Column("client_data.first_name", "user"), webGrid.Column("Name", "Name"), webGrid.Column("Data", "Image", format: @<text>
                                                                                                                                                                                                                 @{
                                                                                                                                                                                                                     var postedFileExtension = Path.GetExtension(item.name);
                                                                                                                                                                                                                     if (string.Equals(postedFileExtension, ".pdf", StringComparison.OrdinalIgnoreCase))
                                                                                                                                                                                                                     {
                                                                                                                                                                                                                         <body>
                                                                                                                                                                                                                         <a href="data:@item.content_type;base64,@Convert.ToBase64String(item.Data)" target="_blank" name="@item.name">
                                                                                                                                                                                                                             view
                                                                                                                                                                                                                         </a>
                                                                                                                                                                                                                         </body>
                                                                                                                                                                                                                     }
                                                                                                                                                                                                                     else
                                                                                                                                                                                                                     {
                                                                                                                                                                                                                         <a href="data:@item.content_type;base64,@Convert.ToBase64String(item.Data)" target="_blank">
                                                                                                                                                                                                                             <object data="data:@item.content_type;base64,@Convert.ToBase64String(item.Data)" type="@item.content_type" width="500px">
                                                                                                                                                                                                                                 <embed src="data:@item.content_type;base64,@Convert.ToBase64String(item.Data)" type="@item.content_type"/>
                                                                                                                                                                                                                             </object>
                                                                                                                                                                                                                         </a>
                                                                                                                                                                                                                     }
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                 
                                                                                                                                                                                                              </text>)))